### ISSUE TITLE
loading Captcha lib

### ISSUE THREAD

**Issue by abusedmedia** [todotoit/cryptoloji#54]
We need to show some waiting_msg/spinner during the captcha loading, it takes a while the first time.

**Comment by alemartina** [comment]
Time to design a spinner for the website.
Or we just use a standard one and will design it later when we'lle have the
resorces

On Tuesday, February 23, 2016, Fabio Franchino <notifications@github.com>
wrote:

> We need to show some waiting_msg/spinner during the captcha loading, it
> takes a while the first time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/todotoit/cryptoloji/issues/54>.
>


-- 
Sent from my phone

**Comment by endorama** [comment]
The loading has been implemented via a simple feedback ( `Loading...` ).

@Giorgio-Olivero could you open a new issue for the spinner if it's the case?

**Comment by Giorgio-Olivero** [comment]
maybe you could implement something from 

- https://github.com/lukehaas/css-loaders
- http://projects.lukehaas.me/css-loaders/

one of these three could be nice: https://www.dropbox.com/s/0qikrm48criyke6/Screenshot%202016-02-24%2014.25.06.png?dl=0
let's try with the third one. I'm suggesting the one based on circles because later on we could actually also use some emoji yellow faces to 'pimp' them.
